---
title: "Introduction to Data Science"
author: "Taylor Arnold"
date: "2020-08-25"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [default, metropolis, metropolis-fonts]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, inverse, middle, title-slide

# Part 1: Welcome!

---

# Welcome!

Welcome to Introduction to Data Science!

It is certainly shaping up to be a strange year. I am looking forward to the semester and
hoping to finding was to get to know you all remotely and to make this course as fun and
rewarding an experience as it usually is.

--

Today we are going to go through these notes, which give a long-form version of the
posted syllabus.

If at any point today, or anytime during the semester, you have a question. Please either
(i) use the Zoom raise hand feature, (ii) post your question or just a question mark in the
chat window, or (iii) wait for a pause and shout out directly.

---

# Website

We will get to all of the course details (grades, assignments, expectations, and so on)
soon. Before that, as reminder from my emails to the class, all of the materials, for the
course can be found on the course website:

- https://statsmaths.github.io/stat289-f20/

Make sure to bookmark this somewhere easy to access. The page will remain online
indefinitely for your reference following the semester.

---
class: center, inverse, middle, title-slide

# Part 2: Course Content

---

# Description

Data science is an interdisciplinary field concerned with drawing knowledge from data and
communicating those results to various audiences. Data science needs to be learned
*by doing* data science.

--

This course broadly covers the entire process of collecting, cleaning, visualising,
modelling, and presenting information for data. It has a MATH designation but is not a
mathematics course. The focus is on applied statistics and data analysis rather than a
detailed study of symbolic mathematics.

--

By the end of the semester you will feel confident collecting, analysing, and writing
about datasets from a variety of fields. You will be able to use these skills to address
data-driven problems in a wide range of application domains.

---

# Example analysis: Hans Roslin (2004)

As an example of the kinds of analysis that we want to make possible, let's watch this short
video presentation by Hans Roslin showing an analysis of 400 years of macroeconomic data:

- https://www.youtube.com/watch?v=jbkSRLYSojo

Do pay attention, as I will use this video as a reference throughout the next few weeks.

---

# Outline

The course content is broken roughly into two parts. In the first we learn so core
techniques for working with data. These notes take about 6 weeks of the semester to cover,
focusing on four main tasks:

1. Creating and organising data using a tabular data model.
2. Learning and applying a theory for data visualisation (Grammar of Graphics).
3. Learning and applying a theory for data manipulation (data table verbs).
4. Learning and applying a method for storytelling with data.

--

And in the second part, we will apply these core methods to specific tasks. These include:

5. Methods for working with textual data.
6. Methods for working with spatial data.
7. Methods for working with network data.
8. Techniques for collecting and organising data from a web-based API.

The specific applications may change slightly based on the pace of the course and student
interest.

---

# Prerequisites and MATH209

The pace of this course assumes that students have had some prior exposure to a programming
language and have taken a course in which statistical techniques were applied to the
analysis of real-world datasets. However, **this is not a strict prerequisite**! Just be
prepared to put in some extra effort earlier on in the semester.

We receive a lot of questions about the relationship between MATH209 and MATH289. The first
focuses a bit more on statistical inference, whereas the second is more oriented towards
building a toolkit of computational models for working with data. The exact material covered
in either depends as much as on who the instructor is as it does the course number.

---
class: center, inverse, middle, title-slide

# Part 3: Format

---

# Online Format

Due to social distancing guidelines and the need to maximize flexibility, Data Science is
being taught using online instruction. Classes will be presented remotely over Zoom. A link
to the Zoom room is provided on the course website. A numeric password was sent via email
to the class roster.

The course has been designed so that only minimal changes will be needed in the event that
some or all students need to return home before the normal end of the semester.

---

# Course Format

Most class meetings will be organised as follows:

- announcements and general questions,
- present answers to previous homework assignment (called a *lab*),
- walk through new material,
- begin working on the next homework assignment.

Sometimes the new material will involve an interactive activity, but usually it will consist
of a short lecture with interspersed questions.

---

# Homework Labs

Most classes have a homework assignment called a *lab* associated with it. These take the
form of a partially completed R markdown file (more on this next time) that must be filled
in with code and short responses.

--

You are expected to make an attempt at completing assigned labs prior to the following
class meeting. These assignments, however, are neither handed in nor given a particular
grade. Instead, you must fill out the **Lab Form** for each lab, which
is linked to from the course website.

--

We will start working on these in-class (format for this semester still to be determined),
and many students often finish the assignment before the end of the course time.

---

# Projects

There will be several (3-5) class projects assigned throughout the semester. Projects will
be distributed with a rubric and graded with a corresponding letter grade. Note that the
projects are concentrated at the end of the semester, because we need to have enough
of the core course material before it makes sense to start applying it to specific
applications.

---

# Attendance Policies

In order to be as flexible as possible given the many uncertainties presented by the
semester ahead, we will have the following attendance policies:

- all course materials (notes, labs, solutions, announcements, ect.) will be posted on the
course website
- class attendance is not required, but is strongly recommended
- synchronous classes will not be recorded
- you may attend the synchronous class meeting for either section (13h30 or 15h00)
- if you do attend the course session, I expect you to arrive at the start of the class
and participate in all of that day's activities

Additional office hours, given as open Zoom sessions, will be listed on the course website.
These are not a replacement for attending class.

---

# Grades

In order to get a satisfactory grade for the course, students are generally expected to:

- keep up with the course material throughout the semester, either through synchronous
attendance or asynchronously following the course notes,
- submit Lab Forms before the next class meeting, for most class meetings (rule of thumb:
miss at most two),
- submit passing versions of all of the assigned projects by their due dates.

Assuming all of the above expectations are met, final grades will be determined by taking
an unweighted average of all your project grades.

---

# Special Circumstances

I completely understand that extenuating circumstances may arise throughout the semester
that effect your ability to follow along with the pace of the course. Please contact me as
soon as possible so that we can find the best path forward.

---

# Frequently Asked Questions

- **Is there a textbook for the course?** No, we will be using my own notes and references
to other freely available resources.
- **Is there a final exam?** No.
- **When are the projects due?** The last project will be due on the last day of class.
Dates and instructions for other projects depend on the pace of the course, but will always
be posted at least three weeks prior to their due date.
- **What software will we be using?** We will be writing code using the R programming
language using a new platform called RStudio Cloud. More on this next time. Classes will
be held using Zoom and projects will be submitted using Box.

---
class: center, inverse, middle, title-slide

# Part 4: Introductions

---

# Me!

- From New England: born in Maine, school in MA, ME, CT
- Research on large text and image datasets in linguistics and cultural studies
- Came to Richmond in 2016
- Last year in Lyon, France
- Some previous work:
    - IBM (Healthcare)
    - Travelers (Insurance)
    - DARPA (social media)
    - AT&T (location analytics)
- Own a Shih-Tzu named Sargent (you will likely see and hear him at some point)

---

# You?

It would be great to get to know all of you now as well. Please fill out the follow form
(a link is on the main website as well):

- https://forms.gle/gdVEoVAEoDLQCaEP7

We will be collecting additional data about ourselves throughout the semester as well,
but this is a good way to get started.
