---
title: "Project 02"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

```{r, include=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
library(smodels)
library(stringi)

theme_set(theme_minimal())
options(dplyr.summarise.inform = FALSE)
options(width = 77L)

movies <- read_csv(file.path("data", "movies_50_years.csv"))
m_genre <- read_csv(file.path("data", "movies_50_years_genre.csv"))
m_people <- read_csv(file.path("data", "movies_50_years_people.csv"))
m_dict <- read_csv(file.path("data", "movies_50_years_data_dictionary.csv"))
m_color <- read_csv(file.path("data", "movies_50_years_color.csv"))
```

## Overview

The goal of this project is to demonstrate your ability to doing something
interesting and non-trivial with the movies dataset. The final output will be
this RMarkdown file *knit* into HTML. More detailed instructions are given
on the Project 2 page linked to from the course website.

**Project Team**:

**Thesis Statement**:

## Project

```{r}

```
