---
title: "Project 04"
output:
  html_document:
    theme: cosmo
    highlight: zenburn
    css: "note-style.css"
---

```{r, include=FALSE, message=FALSE}
library(tidyverse)
library(ggrepel)
library(smodels)
library(stringi)
library(lubridate)
library(sf)
library(units)
library(RcppRoll)
library(hms)

theme_set(theme_minimal())
options(dplyr.summarise.inform = FALSE)
options(width = 77L)
options(lubridate.week.start = 1)
Sys.setlocale(locale = "en_US.UTF-8")

sm_centroid <- function(data) {
  suppressWarnings({ z <- st_coordinates(st_centroid(data)) })
  return(tibble(lon = z[,1], lat = z[,2]))
}
spatial_join <- function(...) {
  return(st_as_sf(as_tibble(st_join(...))))
}

comarea <- read_sf(file.path("data", "chicago_community_areas.geojson"))
ziparea <- read_sf(file.path("data", "zip_codes.geojson"))
socio <- read_csv(file.path("data", "census_socioeconomic.csv"))
medical <- read_csv(file.path("data", "chicago_medical_examiner_cases.csv.gz"))
#crimes <- read_rds(file.path("data", "chicago_crimes_2001_2020_sample.rds"))
crimes <- bind_rows(
  read_csv(file.path("data", "chicago_crimes_2001_2011.csv.gz")),
  read_csv(file.path("data", "chicago_crimes_2012_2020.csv.gz"))
)
schools <- read_sf(file.path("data", "chicago_schools.geojson"))
police <- read_sf(file.path("data", "chicago_police_stations.geojson"))
```

## Overview

See the project description for instructions. The final output will be
this RMarkdown file *knit* into HTML. More detailed instructions are given
on the Project 4 page linked to from the course website.

**Project Team**:

**Community Area**:

**Crime Type**

## Project 04

### Description of Community Area

```{r}
comarea %>%
  st_transform(26972) %>%
  ggplot(aes(label = comarea_name)) +
    geom_sf(size = 0) +
    geom_sf(fill = "navy", data = filter(comarea, comarea == 3)) +
    geom_sf_label(data = filter(comarea, comarea == 3), nudge_x = 6000) +
    labs(x = "", y = "", title = "Uptown Community Area in Chicago, IL")
```

```{r}
socio %>%
  ggplot(aes(hh_poverty, income, size = population)) +
    geom_point(color = "grey85") +
    geom_point(color = "navy", data = filter(socio, comarea == 3)) +
    geom_text(
      aes(label = comarea_name),
      color = "navy",
      data = filter(socio, comarea == 3),
      nudge_x = 5 
    ) +
    labs(x = "", y = "", size = "", title = "")
```


### Crime Rate

```{r}

```


### Multivariate Analysis

```{r}

```


### COVID-19

```{r}

```
